import Head from 'next/head'
import os from 'os'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { NextPage } from "next";
import { getVersion } from './api/version';

const inter = Inter({ subsets: ['latin'] })

type HomeProps = {
  websiteTitle: string
  by: string;
  byHost: string;
  hostname: string;
  version: string;
}

const Home: NextPage<HomeProps> = (props) => {
  console.log('props', props);
  return (
    <>
      <Head>
        <title>{props.websiteTitle} (by: {props.by})</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href={`https://${props.byHost}`}
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <code className={styles.code}>{props.by}</code>
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.description}>
            <h1>
              <code className={styles.code}>{props.websiteTitle}</code>
            </h1>
          </div>
        </div>

        <div className={styles.description}>
          <code className={styles.code}>{props.hostname}</code>
          <code className={styles.code}>version: {props.version}</code>
        </div>
      </main>
    </>
  )
}


export async function getServerSideProps(context: any) {
  let hostname = null;
  let servername = process.env.TITLE;

  const showHostname = process.env.SHOW_HOSTNAME;
  const useHostname = process.env.USE_HOST_NAME;
  const version = getVersion().version;

  if (showHostname === 'true') {
    hostname = os.hostname()
  }

  if (useHostname === 'true') {
    servername = context.req.headers.host;
  }

  const title = servername;
  const by = process.env.BY || 'm2stacklab';
  const byHost = process.env.BY_HOST || 'm2stacklab.io';

  return {
    props: {
      websiteTitle: title,
      by,
      hostname,
      byHost,
      version
    }
  }
}

export default Home;
