import Head from 'next/head'
import os from 'os'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {NextPage} from "next";

const inter = Inter({ subsets: ['latin'] })

type HomeProps = {
  websiteTitle: string
  by: string;
  byHost: string;
  hostname: string;
}

const Home: NextPage<HomeProps> = (props) => {
  console.log('props', props);
  return (
    <>
      <Head>
        <title>{props.websiteTitle} (by: {props.by})</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href={`https://${props.byHost}`}
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <code className={styles.code}>{props.by}</code>
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.description}>
            <h1>
              <code className={styles.code}>{props.websiteTitle}</code>
            </h1>
          </div>
        </div>

        <div className={styles.description}>
          <code className={styles.code}>{props.hostname}</code>
        </div>
      </main>
    </>
  )
}


export async function getServerSideProps() {
  let hostname = null;
  const showHostname = process.env.SHOW_HOSTNAME;
  if (showHostname === 'true'){
    hostname = os.hostname()
  }
  const title =  process.env.TITLE || 'm2stacklab';
  const by =  process.env.BY || 'm2stacklab';
  const byHost = process.env.BY_HOST || 'm2stacklab.io';
  return {
    props: {
      websiteTitle: title,
      by,
      hostname,
      byHost
    }
  }
}

export default Home;
