name: Build website application
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm install
      - name: Build app
        run: npm run build
